/* 
**  mod_index_json.c -- Apache sample index_json module
**  [Autogenerated via ``apxs -n index_json -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_index_json.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /index_json in as follows:
**
**    #   httpd.conf
**    LoadModule index_json_module modules/mod_index_json.so
**    <Location /index_json>
**    SetHandler index_json
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /index_json and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/index_json 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_index_json.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"
#include "apr_strings.h"
#include "apr_file_info.h"

/* The sample content handler */
static int index_json_handler(request_rec *r)
{
  if(strcmp(r->handler, "index_json")) {
    return DECLINED;
  }
  r->content_type = "text/json";

  if(!r->header_only) {
    apr_dir_t* dir;
    apr_finfo_t finfo;
    int count = 0;
    if(apr_dir_open(&dir, r->filename, r->pool)!=APR_SUCCESS) return DECLINED;
    ap_rputs("[", r);
    while(apr_dir_read(&finfo, 0/*APR_FINFO_XXX*/, dir)==APR_SUCCESS) {
      if(finfo.name[0]!='.') {
        if(count>0) ap_rputs(",", r);
        ap_rprintf(r, "\"%s\"", finfo.name);
        count++;
      }
    }
    ap_rputs("]\n", r);
    apr_dir_close(dir);
  }

  return OK;
}

static void index_json_register_hooks(apr_pool_t *p)
{
  ap_hook_handler(index_json_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA index_json_module = {
  STANDARD20_MODULE_STUFF, 
  NULL,                     /* create per-dir    config structures */
  NULL,                     /* merge  per-dir    config structures */
  NULL,                     /* create per-server config structures */
  NULL,                     /* merge  per-server config structures */
  NULL,                     /* table of config file commands       */
  index_json_register_hooks /* register hooks                      */
};

